### ISSUE TITLE
Implementation and Documentation Issues

### ISSUE THREAD

**Issue by entangledloops** [johnnyapol/libgdx-udp-extension#4]
First, I realize this project is 3 years old and I also appreciate what you're doing here, so take these comments as constructive criticism. I was going to try this API, but I found too much inaccuracy in the documentation and API.

- I've noticed some of your methods have inconsistent implementations. For example, look at the methods in class `Packet`. Some of them check for `null` on the input, others have side effects like calling close on input streams, others do not. Why?
- Why do your methods (e.g. `readDouble`) return boxed types like `Double` when the underlying `DataInputStream` actually returns unboxed primitives?
- Why do you refer to member objects with `this` alternatively within methods? Have a look at `readDatagram`, which doesn't at first and then does.
- Your class `UDPManager` is arguably misnamed, as it isn't a UDP Manager at all. If anything, it's a single UDP socket manager, but it's hardly that. It's a place for the user to implement, so by java standards it's really a `UDPFactory`.

In the documentation, I take issue with improper reasons listed for throwing exceptions. For example, `Packet::createDatagram` claims to throw an `IOException`: 
> @throws IOException If there was an error retrieving the data */

But why is a method dedicated to creating datagrams doing any "retrieving of data"? If you look at the implementation, it actually isn't. It's calling `flush` on a `DataOutputStream`, so if anything, it's writing data.

I suggest you carefully review this file, as it contains many such inaccuracies which are confusing for someone trying to use this API.

**Comment by johnnyapol** [comment]
Hi entangledloops,

I appreciate you taking the time to write up about all these issues. This library, I won't lie, is effectively garbage reflecting on it now. I actually wrote this when I was about 14 years old I think and I was still very much a novice at the time. I was very focused on "reinventing the wheel" for pride rather than just accepting that there were far better engineered solutions than what I was (and probably still am) capable of creating.

I realize that there probably is a demand for a clean, lightweight, and basic UDP library that is simply to use. I hope at some point when I have more free time I can do a proper rewrite of this library.

Thank you for your feedback and I apologize for seeing this so late. While I may have activity on this account, it is mostly private repositories for personal and academic stuff so I did not notice your comment until now. 

Closing this out as it will hopefully be resolved when I get around to cleaning it up
